#ifndef OPCODE_TARGETS_H
#define OPCODE_TARGETS_H

static const void* opcode_targets[] = {
	&&TARGET_LOAD_FUNC,
	&&TARGET_LOAD_LOCAL,
	&&TARGET_LOAD_SYM,
	&&TARGET_LOAD_IMPORT,
	&&TARGET_JUMP_IF_FALSE,
	&&TARGET_JUMP_IF_TRUE,
	&&TARGET_JUMP_FORWARD,
	&&TARGET_FUNC_CALL,
	&&TARGET_SET_LOCAL,
	&&TARGET_SET_IN_ENV,
	&&TARGET_LOAD_ENV,
	&&TARGET_LOAD_FROM_ENV,
};

#endif