#ifndef OPCODE_TARGETS_H
#define OPCODE_TARGETS_H

static const void* opcode_targets[] = {
	&&TARGET_LOAD_FUNC,
	&&TARGET_LOAD_CLOSURE,
	&&TARGET_LOAD_LOCAL,
	&&TARGET_LOAD_BIND,
	&&TARGET_LOAD_CONST,
	&&TARGET_PUSH_BOOL,
	&&TARGET_PUSH_NULL,
	&&TARGET_JUMP_IF_FALSE,
	&&TARGET_JUMP_IF_TRUE,
	&&TARGET_JUMP_FORWARD,
	&&TARGET_FUNC_CALL,
	&&TARGET_SET_LOCAL,
	&&TARGET_SET_BIND,
};

#endif