#ifndef OPCODES_H
#define OPCODES_H

/* Generated by gen-headers.scm, do not edit. */

#define OP_CASE(code) case code: return #code

#define LOAD_FUNC	0x0	/* Load function local to module */
#define LOAD_CLOSURE	0x1	/* Make closure on heap */
#define LOAD_LOCAL	0x2	/* Load object from frame-local area */
#define LOAD_BIND	0x3	/* Load object form binding */
#define LOAD_CONST	0x4	/* Load object from module constant area */
#define PUSH_BOOL	0x5	/* Push boolean value */
#define PUSH_NULL	0x6	/* Load built-in constant */
#define JUMP_IF_FALSE	0x7	/* Jump if false */
#define JUMP_FORWARD	0x8	/* Jump forward */
#define FUNC_CALL	0x9	/* Call function */
#define SET_LOCAL	0xa	/* Assign new value to local binding */
#define SET_BIND	0xb	/* Asign new value to non-local binding */

#define OT_FIXNUM	0x0	/* Fixed number */
#define OT_CHARACTER	0x1	/* Character */
#define OT_STRING	0x2	/* String */
#define OT_SYMBOL	0x3	/* Symbol */
#define OT_STATIC	0x4	/* Static variable */
#define OT_PAIR_BEGIN	0x5	/* Pair begin */
#define OT_PAIR_END	0x6	/* Pair end */
#define OT_VECTOR_BEGIN	0x7	/* Vector begin */
#define OT_NULL	0x8	/* Null object */

static inline const char* opcode_name(int code)
{
	switch (code) {
		OP_CASE(LOAD_FUNC);
		OP_CASE(LOAD_CLOSURE);
		OP_CASE(LOAD_LOCAL);
		OP_CASE(LOAD_BIND);
		OP_CASE(LOAD_CONST);
		OP_CASE(PUSH_BOOL);
		OP_CASE(PUSH_NULL);
		OP_CASE(JUMP_IF_FALSE);
		OP_CASE(JUMP_FORWARD);
		OP_CASE(FUNC_CALL);
		OP_CASE(SET_LOCAL);
		OP_CASE(SET_BIND);
	}
	return "unknown";
}

static inline const char* object_type_name(int code)
{
	switch (code) {
		OP_CASE(OT_FIXNUM);
		OP_CASE(OT_CHARACTER);
		OP_CASE(OT_STRING);
		OP_CASE(OT_SYMBOL);
		OP_CASE(OT_STATIC);
		OP_CASE(OT_PAIR_BEGIN);
		OP_CASE(OT_PAIR_END);
		OP_CASE(OT_VECTOR_BEGIN);
		OP_CASE(OT_NULL);
	}
	return "unknown";
}

#endif
