(library (sc syntax-pattern)
  (export pattern-match pattern-bind)
  (import (rnrs base)
          (format)
          (sc syntax-core))
  
  (define (ellipsis-pair? pat)
    (and (pair? pat)
         (pair? (cdr pat))
         (eq? (cadr pat) '...)))

  (define (initial-merge pat xpr)
    (cond ((pair? pat)
           (cons (initial-merge (car pat) (car xpr))
                 (initial-merge (cdr pat) (cdr xpr))))
          ((null? pat) '())
          (else (list xpr))))

  (define (pattern-merge pat xpr1 xpr2)
    (cond ((null? xpr2) (initial-merge pat xpr1))
          ((pair? pat)
           (cons (pattern-merge (car pat) (car xpr1) (car xpr2))
                 (pattern-merge (cdr pat) (cdr xpr1) (cdr xpr2))))
          (else (cons xpr1 xpr2))))

  (define (pattern-match reserved xpr pat)
    (call/cc
     (lambda (return)
       (define (match-ellipsis xpr pat)
         (cond ((syntax-null? xpr) '())
               ((syntax-pair? xpr)
                (pattern-merge pat (match (syntax-car xpr) pat)
                               (match-ellipsis (syntax-cdr xpr) pat)))
               (else (return #f))))
       
       (define (match xpr pat)
         (cond ((ellipsis-pair? pat)
                (let ((elm (match-ellipsis xpr (car pat))))
                  (if (pair? (car pat))
                      elm
                      (list elm))))
               ((or (syntax-null? xpr)
                    (null? pat))
                (if (and (syntax-null? xpr)
                         (null? pat))
                    '()
                    (return #f)))
               ((pair? pat)
                (if (syntax-pair? xpr)
                    (cons (match (syntax-car xpr) (car pat))
                          (match (syntax-cdr xpr) (cdr pat)))
                    (return #f)))
               ((eq? pat '_) '())
               ((symbol? pat) xpr)
               ((equal? pat (syntax-object-expr xpr)) '())
               (else (return #f))))
       
       (match xpr pat))))

  (define (pattern-bind xpr pat vars)
    (cond ((ellipsis-pair? pat)
           (append xpr vars))
          ((pair? pat)
           (pattern-bind (car xpr) (car pat)
                         (pattern-bind (cdr xpr) (cdr pat) vars)))
          ((eq? pat '_) vars)
          ((symbol? pat)
           (cons xpr vars))
          (else vars)))
  )
